### ISSUE TITLE
When creating new items, there is no Blank weight option, yet in the game all containers have no weight. So if they are created as items, it throws off encumbrance. 

### ISSUE THREAD

**Issue by cleverername** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#17]

**Comment by giant-teapot** [comment]
Maybe something could be done around this for the sake of clarity, but I believe it is actually supported: simply create the item as "tiny".
Since tiny items explicitly don't contribute towards the encumbrance, it's what you want to use most of the time.

Now you are correct: there is the special case for containers (bags, pouches, bougettes and the like). Although it's a good workaround, it is somewhat odd to register them as "tiny" (because that's not necessarily true).

**Comment by lasseborly** [comment]
I'll gladly submit a PR for this 😊

What about making a "duplicate" option of tiny that is simple called "container"? Solving the wording problem that way? Or would we rather have "Blank", "None"?

**Comment by aMediocreDad** [comment]
This will be solved in the next release. Adding a "None" class to the weight table as this should encompass worn clothes, containers and the like.
