### ISSUE TITLE
🐛 Combat tracker and "templates" and "assets" folders content, all disappeared in 9.0.1

### ISSUE THREAD

**Issue by GreatTarkus** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#225]
**Description**
With new 9.0.1. version, Combat Tracker has stopped working completely. 
Besides, art content from folders Assets and Templates has been deleted. 

**Desktop**
OS: Win 10
Foundry Desktop app
Foundry version 9, build 269.

**Additional context**
Coincidentally, all art from Official Modules has disappeared with the last update too. Warned, Fria Ligan, no answer.

**Comment by aMediocreDad** [comment]
Hey there! Thanks for logging an issue.

>  With new 9.0.1. version, Combat Tracker has stopped working completely.
In 9.0.0 the combat tracker was overhauled. Make sure you have no other modules that affect the combat tracker running as those may interfere with how the combat tracker works.

> Besides, art content from folders Assets and Templates has been deleted.
I am not sure what you are referring to here. What Assets and Templates folders? The Templates folder contains no art, it only contains the `.hbs` templates the game utilizes. In Assets there is some art used for rendering the UI. If any art is gone from that folder the game won't render properly.

>  Coincidentally, all art from Official Modules has disappeared with the last update too. Warned, Fria Ligan, no answer.

Have you updated the official modules? I checked the latest Core Game release zip, and it contains all original art assets along with newly added cards.

**Comment by mattsildo** [comment]
I cannot say if his problem was the same as mine, but I think it is. I updated from Foundry 0.8.9 to 9 today and all my official journals from the modules are gone. I tried to import again but it didn't solve. Crazy

**Comment by aMediocreDad** [comment]
> Still same issues. Desintalled Forbidden Lands System, reinstalled, and created a new world without any active modules. No combat tracker, no art.
> 
> 
> 
> ![4](https://user-images.githubusercontent.com/106348523/176016717-0cf33a12-ec33-44ca-9a40-0ea88472c7b0.png)
> 
> 
> 
> ![3](https://user-images.githubusercontent.com/106348523/176016695-b9cac683-cec1-403a-a34a-b9fbcbe7e969.png)
> 
> 
> 
> ![1](https://user-images.githubusercontent.com/106348523/176016766-becef1ef-b680-4e1f-8934-245f8db24378.png)
> 
> 
> 
> The assets folder should look like this (previous version I've backed up) :
> 
> 
> 
> ![2](https://user-images.githubusercontent.com/106348523/176016871-b6dfaae5-ef59-4e04-b3c6-dd6608362903.png)
> 
> 
> 
> 

Difficult to tell what causing this problem, as you attempt to reinstall the system. 

- Where are you installing the system from (the system browser in foundry or a manifest)? 
- Could there be a possibility that Foundry does not have write access to the systems folder anymore? 
- Have you verified the system disappears as you uninstall it?
- Alternately, try deleting the system folder instead of uninstalling.
- Another possibility is that there is something corrupt in Foundry's electron instance. It could be worth attempting to reinstall foundry.
- Finally, try downloading the latest release from the releases page manually. Unzip it in the systems folder and make sure it is named `forbidden-lands`. Also check that the assets are there.

**Comment by GreatTarkus** [comment]
Ok, tried to install the system from the zip, but Foundry told me there is an error and have to update it.

After that, I tried to reinstall the system via json Manifest URL instead, and it works as intended.

Looks like Foundry system installer is taking it from other place.

Thanks.
