### ISSUE TITLE
Strange font behavior on Linux/Ubuntu 20.04

### ISSUE THREAD

**Issue by MichalKolesinski** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#93]
I've got that strange font look when I run Forbidden Lands on Linux. On Windows all is fine. All looks fine when I join the game by the browser, so it may be as well Foundry related. 

![Screenshot1](https://user-images.githubusercontent.com/39199872/115138440-78c34380-a02c-11eb-8216-c3ab872073f5.png)
![Screenshot2](https://user-images.githubusercontent.com/39199872/115138443-7d87f780-a02c-11eb-8342-7e4f19359f7f.png)

**Comment by aMediocreDad** [comment]
Hey! I think I know what's going on here. 

Unfortunately I cannot test a fix of this. But I'll do a silent release later today so you can check whether it solves your problem.

**Comment by aMediocreDad** [comment]
@MichalKolesinski Hello!

I have fixed this in the main system, and am submitting the fixes to official modules soon. The reason you are experiencing this issue is that the modules haven't been updated yet. I tried not to break things with the modules knowing that it will take some time between me shipping the updates to the modules and Free League updating them in Foundry (I do not have control over the release of the official modules, unfortunately).

**Comment by MichalKolesinski** [comment]
Hi!
I can already see the fix in the character generator, great job! Thanks to Foundry I've found out about Forbidden Lands and started playing this wonderful RPG. I just want you to know that your effort is highly enjoyed and appreciated. Thank you!
