### ISSUE TITLE
Problems after upgrading to 5.1.2

### ISSUE THREAD

**Issue by tbergstedt** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#98]
I just upgraded the game system from 4.1.2 to 5.1.1 in my local FoundryVTT installation, trying it out before doing the same in my official server-based one. But I seem to be having some issues:
 - The _push roll_ macro does not work anymore. Web console output shows
    ``` 
    TypeError: Cannot read property 'dices' of undefined
    at DiceRoller.push (forbidden-lands.js:1022)
    at eval (eval at execute (foundry.js:32837), <anonymous>:1:19)
    at Macro.execute (foundry.js:32837)
    at Hotbar._onClickMacro (foundry.js:20566)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2) 
    ```
- At the same time, I cannot see the **Push** button on any rolls (generic or from an item)

The new _Party_ character seems to be in place, so some of the upgrade has come through.

I simply did the upgrade from within FoundryVTT, is there more I need to do?

**Comment by aMediocreDad** [comment]
Hi there! The push macro does not work anymore since dice rolls work a bit differently since we now have pushing on the chat message instead.

You can change the macro to `CONFIG.diceRoller.push(CONFIG.diceRoller)`, but this only allows you to push the last generic roll (using the dice roller macro).

If you as a GM wants the possibility to push rolls you can disable the restriction in system settings. The setting is called "Allow Unlimited Pushing".

**Comment by tbergstedt** [comment]
Thanks for such a quick reply. I would be fine with not having a macro for pushing anymore, but the thing is that the **Push** button in chat messages seems missing:
![image](https://user-images.githubusercontent.com/5285126/115354906-6ecf4b00-a1ba-11eb-9362-79e4f08cf7de.png)

And I can't see any "Allow Unlimited Pushing" under System Settings:
![image](https://user-images.githubusercontent.com/5285126/115355011-8a3a5600-a1ba-11eb-8c91-fec596a78d69.png)

This makes me suspect that the upgrade is only partial. I have restarted the system, but I guess there's more I need to do?

As you might undertand, I'm reluctant to do the same on my server-based system until I at least know what to do to fix this.

**Comment by aMediocreDad** [comment]
That looks a bit strange. The "Allow Pushing Travel Rolls" has an old translation string. It is supposed to be named "Allow Unlimited Pushing".

Just to be certain I would delete the System and reinstall it. (Do not delete your world).

**Comment by tbergstedt** [comment]
There seems to be some problem when upgrading an existing world. I tried creating a new world based on v5.1.2. And in that one, I get the **Push** button on all rolls - but only if I check the "Allow Unlimited Pushing" setting.

I did Uninstall via FoundryVTT and made sure the /systems folder was cleared. I have updated the worlds after that, and installed the new module version. Performed  a new Import after that.

In the pre-existing world, I still have the old setting "Allow Pushing Travel Rolls". I do have the character sheet and can use the new Push action from that, but would prefer some simpler way of performing such rolls.

**Comment by aMediocreDad** [comment]
I am not sure what you want out the system at this point.

In 5.1.2, and going forward we are using the chat messages to provide a button for pushing.

GMs by default in the rules are not allowed to push rolls, thus the button is disabled for the GM. If you want to be able to interact with the push button on chat messages as a GM, you need to enable Unlimited Pushing (I noticed this applies to all clients when the GM enables it. It should be an individual client setting, so this will be fixed).

The setting issue you see is likely because you have the Party Sheet module loaded, you need to disable it.

Pushing rolls from macros is not possible at the moment because the way rolls are handled was changed to enable the Push-button on chat messages.

**Comment by tbergstedt** [comment]
So then it was just a matter of misunderstanding, I think. I tried logging in as player, and everything seems to work fine then regarding pushed rolls. I have no need to any Push macro, that was just a matter of having an altrnative when I (incorrectly) thought  that Pushing didn't work. 

Not entirely sure about that old settings name that seemed to stick - might have just been missing a module update or similar.

Thanks for clearing this up for me!
